# Generated by Django 5.2 on 2026-05-26 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("practice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("CONSULTATION", "Consultation"),
                            ("WELL_CHILD_VISIT", "Well-child visit"),
                            ("FOLLOW_UP", "Follow-up"),
                            ("EMERGENCY", "Emergency"),
                            ("VACCINATION", "Vaccination"),
                            ("OTHER", "Other"),
                        ],
                        default="CONSULTATION",
                        max_length=20,
                        verbose_name="encounter type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True, verbose_name="scheduled at")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="started at")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="completed at")),
                ("reason_for_visit", models.TextField(blank=True, verbose_name="reason for visit")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="doctor",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters",
                        to="practice.location",
                        verbose_name="location",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "encounter",
                "verbose_name_plural": "encounters",
                "db_table": "encounters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Optional ICD-10 code, e.g. J06.9",
                        max_length=20,
                        verbose_name="ICD-10 code",
                    ),
                ),
                ("description", models.CharField(max_length=500, verbose_name="description")),
                ("is_primary", models.BooleanField(default=False, verbose_name="primary diagnosis")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="medical_records.encounter",
                        verbose_name="encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "diagnosis",
                "verbose_name_plural": "diagnoses",
                "db_table": "diagnoses",
            },
        ),
        migrations.CreateModel(
            name="Anthropometry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True, verbose_name="weight (kg)"
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="height (cm)"
                    ),
                ),
                (
                    "head_circumference_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="head circumference (cm)"
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-calculated from weight and height.",
                        max_digits=5,
                        null=True,
                        verbose_name="BMI",
                    ),
                ),
                (
                    "weight_for_age_z",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="weight-for-age Z"
                    ),
                ),
                (
                    "height_for_age_z",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="height-for-age Z"
                    ),
                ),
                (
                    "head_circumference_for_age_z",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="head circumference-for-age Z",
                    ),
                ),
                (
                    "bmi_for_age_z",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="BMI-for-age Z"
                    ),
                ),
                (
                    "weight_for_height_z",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="weight-for-height Z"
                    ),
                ),
                (
                    "weight_for_age_percentile",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="weight-for-age percentile"
                    ),
                ),
                (
                    "height_for_age_percentile",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="height-for-age percentile"
                    ),
                ),
                (
                    "head_circumference_for_age_percentile",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="head circumference-for-age percentile",
                    ),
                ),
                (
                    "bmi_for_age_percentile",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="BMI-for-age percentile"
                    ),
                ),
                (
                    "weight_for_height_percentile",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="weight-for-height percentile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anthropometry_records",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anthropometry",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
                (
                    "encounter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anthropometry",
                        to="medical_records.encounter",
                        verbose_name="encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "anthropometry",
                "verbose_name_plural": "anthropometry records",
                "db_table": "anthropometry",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhysicalExam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("general_appearance", models.TextField(blank=True, verbose_name="general appearance")),
                ("skin", models.TextField(blank=True, verbose_name="skin")),
                ("head_neck", models.TextField(blank=True, verbose_name="head and neck")),
                ("eyes", models.TextField(blank=True, verbose_name="eyes")),
                ("ears_nose_throat", models.TextField(blank=True, verbose_name="ears, nose and throat")),
                ("respiratory", models.TextField(blank=True, verbose_name="respiratory")),
                ("cardiovascular", models.TextField(blank=True, verbose_name="cardiovascular")),
                ("abdomen", models.TextField(blank=True, verbose_name="abdomen")),
                ("genitourinary", models.TextField(blank=True, verbose_name="genitourinary")),
                ("musculoskeletal", models.TextField(blank=True, verbose_name="musculoskeletal")),
                ("neurological", models.TextField(blank=True, verbose_name="neurological")),
                ("lymph_nodes", models.TextField(blank=True, verbose_name="lymph nodes")),
                ("additional_findings", models.TextField(blank=True, verbose_name="additional findings")),
                (
                    "encounter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physical_exam",
                        to="medical_records.encounter",
                        verbose_name="encounter",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physical_exams",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "physical exam",
                "verbose_name_plural": "physical exams",
                "db_table": "physical_exams",
            },
        ),
        migrations.CreateModel(
            name="SOAPNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subjective",
                    models.TextField(
                        blank=True,
                        help_text="Patient/tutor complaints and reported symptoms.",
                        verbose_name="subjective",
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        blank=True,
                        help_text="Doctor's direct observations and examination findings.",
                        verbose_name="objective",
                    ),
                ),
                (
                    "assessment",
                    models.TextField(
                        blank=True, help_text="Diagnosis and differential diagnoses.", verbose_name="assessment"
                    ),
                ),
                (
                    "plan",
                    models.TextField(
                        blank=True,
                        help_text="Treatment plan, follow-up instructions, and referrals.",
                        verbose_name="plan",
                    ),
                ),
                (
                    "encounter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soap_note",
                        to="medical_records.encounter",
                        verbose_name="encounter",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soap_notes",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "SOAP note",
                "verbose_name_plural": "SOAP notes",
                "db_table": "soap_notes",
            },
        ),
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="temperature (°C)"
                    ),
                ),
                ("heart_rate", models.PositiveIntegerField(blank=True, null=True, verbose_name="heart rate (bpm)")),
                (
                    "respiratory_rate",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="respiratory rate (rpm)"),
                ),
                (
                    "blood_pressure_systolic",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="blood pressure systolic (mmHg)"),
                ),
                (
                    "blood_pressure_diastolic",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="blood pressure diastolic (mmHg)"),
                ),
                (
                    "oxygen_saturation",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="oxygen saturation (%)"
                    ),
                ),
                (
                    "encounter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_signs",
                        to="medical_records.encounter",
                        verbose_name="encounter",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_signs",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "vital signs",
                "verbose_name_plural": "vital signs",
                "db_table": "vital_signs",
            },
        ),
    ]
