# Generated by Django 5.0.14 on 2026-06-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("name_es", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=50)),
                ("is_common", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Diagnosis catalog entry",
                "verbose_name_plural": "Diagnosis catalog",
                "ordering": ["code"],
            },
        ),
    ]
