# Generated by Django 5.0.14 on 2026-06-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0003_seed_diagnosis_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncounterTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("WELL_CHILD", "Control niño sano"),
                            ("MORBIDITY", "Consulta morbilidad"),
                            ("FOLLOW_UP", "Control seguimiento"),
                            ("VACCINATION", "Vacunación"),
                        ],
                        max_length=20,
                    ),
                ),
                ("age_range_label", models.CharField(blank=True, default="", max_length=50)),
                ("age_min_months", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("age_max_months", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("subjective_template", models.TextField(blank=True, default="")),
                ("objective_template", models.TextField(blank=True, default="")),
                ("assessment_template", models.TextField(blank=True, default="")),
                ("plan_template", models.TextField(blank=True, default="")),
                ("physical_exam_template", models.JSONField(blank=True, default=dict)),
                ("development_checklist", models.JSONField(blank=True, default=list)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Encounter template",
                "verbose_name_plural": "Encounter templates",
                "ordering": ["template_type", "display_order"],
            },
        ),
    ]
