# Generated by Django 5.0.14 on 2026-06-09 23:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0005_seed_encounter_templates"),
        ("patients", "0008_patient_apgar_1min_patient_apgar_5min_and_more"),
        ("practice", "0010_update_account_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VaccineSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("disease", models.CharField(max_length=200)),
                ("dose_label", models.CharField(max_length=50)),
                ("age_months", models.PositiveSmallIntegerField()),
                ("age_label", models.CharField(max_length=50)),
                ("route", models.CharField(blank=True, default="", max_length=50)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Vaccine schedule entry",
                "verbose_name_plural": "Vaccine schedule",
                "ordering": ["age_months", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("vaccine_name", models.CharField(max_length=100)),
                ("dose_label", models.CharField(max_length=50)),
                ("lot_number", models.CharField(blank=True, default="", max_length=50)),
                ("administered_at", models.DateField()),
                ("site", models.CharField(blank=True, default="", max_length=50)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "administered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccinations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="vaccinations", to="patients.patient"
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="vaccinations", to="practice.practice"
                    ),
                ),
                (
                    "vaccine_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="medical_records.vaccineschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaccination",
                "verbose_name_plural": "Vaccinations",
                "ordering": ["-administered_at"],
            },
        ),
    ]
