# Generated by Django 5.0.14 on 2026-06-09 23:10
"""
Data migration: seeds the PNI Chile 2025 vaccination schedule.
Uses bulk_create(ignore_conflicts=True) so re-running is safe.
"""

from django.db import migrations


PNI_ENTRIES = [
    # name, disease, dose_label, age_months, age_label, route, display_order
    # ── Recién nacido ────────────────────────────────────────────────────────
    ("BCG", "Tuberculosis", "Única", 0, "Recién nacido", "intradérmica", 1),
    ("Hepatitis B", "Hepatitis B", "Única", 0, "Recién nacido", "IM", 2),
    # ── 2 meses ──────────────────────────────────────────────────────────────
    ("Hexavalente (DTPa-IPV-Hib-HepB)", "Difteria, Tétanos, Pertussis, Polio, Hib, Hepatitis B", "1ra dosis", 2, "2 meses", "IM", 3),
    ("Neumocócica conjugada", "Enfermedad neumocócica", "1ra dosis", 2, "2 meses", "IM", 4),
    ("Rotavirus", "Gastroenteritis por rotavirus", "1ra dosis", 2, "2 meses", "oral", 5),
    # ── 4 meses ──────────────────────────────────────────────────────────────
    ("Hexavalente (DTPa-IPV-Hib-HepB)", "Difteria, Tétanos, Pertussis, Polio, Hib, Hepatitis B", "2da dosis", 4, "4 meses", "IM", 6),
    ("Neumocócica conjugada", "Enfermedad neumocócica", "2da dosis", 4, "4 meses", "IM", 7),
    ("Rotavirus", "Gastroenteritis por rotavirus", "2da dosis", 4, "4 meses", "oral", 8),
    ("Meningocócica conjugada", "Enfermedad meningocócica", "1ra dosis", 4, "4 meses", "IM", 9),
    # ── 6 meses ──────────────────────────────────────────────────────────────
    ("Hexavalente (DTPa-IPV-Hib-HepB)", "Difteria, Tétanos, Pertussis, Polio, Hib, Hepatitis B", "3ra dosis", 6, "6 meses", "IM", 10),
    # ── 12 meses ─────────────────────────────────────────────────────────────
    ("Neumocócica conjugada", "Enfermedad neumocócica", "Refuerzo", 12, "12 meses", "IM", 11),
    ("Meningocócica conjugada", "Enfermedad meningocócica", "Refuerzo", 12, "12 meses", "IM", 12),
    ("SRP (Sarampión-Rubéola-Parotiditis)", "Sarampión, Rubéola y Parotiditis", "1ra dosis", 12, "12 meses", "IM", 13),
    # ── 18 meses ─────────────────────────────────────────────────────────────
    ("Hexavalente (DTPa-IPV-Hib-HepB)", "Difteria, Tétanos, Pertussis, Polio, Hib, Hepatitis B", "Refuerzo", 18, "18 meses", "IM", 14),
    ("Varicela", "Varicela", "Única", 18, "18 meses", "IM", 15),
    ("Hepatitis A", "Hepatitis A", "Única", 18, "18 meses", "IM", 16),
    # ── 36 meses (3-4 años) ───────────────────────────────────────────────────
    ("SRP (Sarampión-Rubéola-Parotiditis)", "Sarampión, Rubéola y Parotiditis", "2da dosis", 36, "3-4 años", "IM", 17),
    # ── 6 años ───────────────────────────────────────────────────────────────
    ("DTPa (refuerzo)", "Difteria, Tétanos y Pertussis acelular", "Refuerzo", 72, "6 años", "IM", 18),
    # ── 9 años ───────────────────────────────────────────────────────────────
    ("VPH (Virus Papiloma Humano)", "Infección por VPH y cáncer cervicouterino", "1ra dosis", 108, "9 años", "IM", 19),
    ("VPH (Virus Papiloma Humano)", "Infección por VPH y cáncer cervicouterino", "2da dosis (6 meses después)", 114, "9 años (6m después)", "IM", 20),
    # ── 14 años ──────────────────────────────────────────────────────────────
    ("dTpa (acelular adulto)", "Difteria, Tétanos y Pertussis (adulto)", "Única", 168, "14 años", "IM", 21),
]


def seed_pni(apps, schema_editor):
    VaccineSchedule = apps.get_model("medical_records", "VaccineSchedule")
    entries = [
        VaccineSchedule(
            name=name,
            disease=disease,
            dose_label=dose_label,
            age_months=age_months,
            age_label=age_label,
            route=route,
            display_order=display_order,
        )
        for name, disease, dose_label, age_months, age_label, route, display_order in PNI_ENTRIES
    ]
    VaccineSchedule.objects.bulk_create(entries, ignore_conflicts=True)


def unseed_pni(apps, schema_editor):
    VaccineSchedule = apps.get_model("medical_records", "VaccineSchedule")
    VaccineSchedule.objects.filter(
        name__in={entry[0] for entry in PNI_ENTRIES}
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0006_vaccineschedule_vaccination"),
    ]

    operations = [
        migrations.RunPython(seed_pni, reverse_code=unseed_pni),
    ]
