# Generated by Django 5.0.14 on 2026-06-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0007_seed_pni_chile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="encounter_type",
            field=models.CharField(
                choices=[
                    ("CONSULTATION", "Consulta"),
                    ("WELL_CHILD_VISIT", "Control sano"),
                    ("FOLLOW_UP", "Seguimiento"),
                    ("EMERGENCY", "Urgencia"),
                    ("VACCINATION", "Vacunación"),
                    ("OTHER", "Otro"),
                ],
                default="CONSULTATION",
                max_length=20,
                verbose_name="encounter type",
            ),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Agendado"),
                    ("IN_PROGRESS", "En curso"),
                    ("COMPLETED", "Completado"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="SCHEDULED",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
