# Generated by Django 5.2 on 2026-05-26 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("practice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient_email", models.EmailField(max_length=254, verbose_name="recipient email")),
                ("subject", models.CharField(max_length=500, verbose_name="subject")),
                (
                    "body_preview",
                    models.TextField(
                        blank=True, help_text="First 500 characters of the email body", verbose_name="body preview"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("QUEUED", "Queued"), ("SENT", "Sent"), ("FAILED", "Failed")],
                        default="QUEUED",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("provider", models.CharField(default="resend", max_length=50, verbose_name="provider")),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Resend message ID returned by the provider",
                        max_length=255,
                        verbose_name="external id",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="sent at")),
                (
                    "practice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "email log",
                "verbose_name_plural": "email logs",
                "db_table": "email_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT_REMINDER", "Appointment Reminder"),
                            ("APPOINTMENT_CONFIRMED", "Appointment Confirmed"),
                            ("APPOINTMENT_CANCELLED", "Appointment Cancelled"),
                            ("WAITLIST_AVAILABLE", "Waitlist Available"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=30,
                        verbose_name="notification type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                ("is_read", models.BooleanField(default=False, verbose_name="is read")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="read at")),
                (
                    "related_type",
                    models.CharField(
                        blank=True,
                        help_text="Model name, e.g. Appointment or Payment",
                        max_length=50,
                        verbose_name="related type",
                    ),
                ),
                (
                    "related_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="Primary key of the related object", null=True, verbose_name="related id"
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_appointment_reminder",
                    models.BooleanField(default=True, verbose_name="email appointment reminder"),
                ),
                (
                    "email_appointment_confirmed",
                    models.BooleanField(default=True, verbose_name="email appointment confirmed"),
                ),
                (
                    "email_appointment_cancelled",
                    models.BooleanField(default=True, verbose_name="email appointment cancelled"),
                ),
                (
                    "email_waitlist_available",
                    models.BooleanField(default=True, verbose_name="email waitlist available"),
                ),
                ("email_payment_received", models.BooleanField(default=True, verbose_name="email payment received")),
                (
                    "reminder_hours_before",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="How many hours before the appointment to send the reminder",
                        verbose_name="reminder hours before",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
                "db_table": "notification_preferences",
            },
        ),
    ]
