# Generated by Django 5.0.14 on 2026-06-09 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_register_alert_schedules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtemplate",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
