# Generated by Django 5.0.14 on 2026-06-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notificationtemplate_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_blog_posts",
            field=models.BooleanField(default=True, verbose_name="email blog posts"),
        ),
    ]
