# Generated by Django 5.0.14 on 2026-06-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_prefix",
            field=models.CharField(blank=True, default="+56", max_length=10, verbose_name="phone prefix"),
        ),
        migrations.AddField(
            model_name="user",
            name="rut",
            field=models.CharField(
                blank=True, help_text="Chilean RUT (e.g. 12.345.678-9)", max_length=12, verbose_name="RUT"
            ),
        ),
    ]
