# Generated by Django 5.0.14 on 2026-06-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_rut_and_phone_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_alt",
            field=models.CharField(blank=True, max_length=30, verbose_name="alternate phone"),
        ),
    ]
