# Generated by Django 5.0.14 on 2026-06-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_phone_alt_and_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("RUT", "RUT (Chilean national ID)"),
                    ("DNI", "Foreign national ID (DNI)"),
                    ("PASAPORTE", "Passport"),
                    ("OTRO", "Other"),
                ],
                default="RUT",
                max_length=20,
                verbose_name="document type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="rut",
            field=models.CharField(
                help_text="Chilean RUT or document number (e.g. 12.345.678-9)",
                max_length=12,
                verbose_name="RUT / document number",
            ),
        ),
    ]
