# Generated by Django 5.0.14 on 2026-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_document_type_require_rut"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="",
                help_text="Profile photo. Max 5 MB, JPEG/PNG/WebP.",
                upload_to="avatars/%Y/%m/",
                verbose_name="avatar",
            ),
        ),
    ]
