# Generated by Django 5.2 on 2026-05-26 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("practice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="slug")),
                (
                    "excerpt",
                    models.TextField(blank=True, help_text="Short summary for listing pages.", verbose_name="excerpt"),
                ),
                ("content", models.TextField(help_text="Full HTML/Markdown content.", verbose_name="content")),
                ("cover_image", models.ImageField(blank=True, upload_to="blog/covers/", verbose_name="cover image")),
                ("is_published", models.BooleanField(default=False, verbose_name="published")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="published at")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags, e.g. salud,pediatría,vacunas",
                        max_length=500,
                        verbose_name="tags",
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=255, verbose_name="meta description")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "blog post",
                "verbose_name_plural": "blog posts",
                "db_table": "blog_posts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("question", models.CharField(max_length=500, verbose_name="question")),
                ("answer", models.TextField(verbose_name="answer")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Controls display order.", verbose_name="order"),
                ),
                ("is_published", models.BooleanField(default=False, verbose_name="published")),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "db_table": "faqs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", models.SlugField(max_length=255, verbose_name="slug")),
                ("content", models.TextField(help_text="HTML content for this page.", verbose_name="content")),
                ("is_published", models.BooleanField(default=False, verbose_name="published")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Controls display order in menus.", verbose_name="order"
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=255, verbose_name="meta description")),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "pages",
                "db_table": "pages",
                "ordering": ["order", "title"],
                "unique_together": {("practice", "slug")},
            },
        ),
    ]
