# Generated by Django 5.0.14 on 2026-06-11 04:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_subscriber_newslettersent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostEngagement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "engagement_type",
                    models.CharField(
                        choices=[("USEFUL", "Useful"), ("LOVE", "Love"), ("RATING", "Rating")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1-5 for ratings, null for reactions", null=True
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "blog_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="engagements", to="content.blogpost"
                    ),
                ),
            ],
            options={
                "verbose_name": "post engagement",
                "verbose_name_plural": "post engagements",
                "db_table": "post_engagements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="postengagement",
            constraint=models.UniqueConstraint(
                fields=("blog_post", "engagement_type", "session_key"), name="unique_engagement_per_session"
            ),
        ),
    ]
