# Generated by Django 5.0.14 on 2026-06-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_post_engagement"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="post_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Auto-assigned sequential number on first publish.",
                null=True,
                unique=True,
                verbose_name="post number",
            ),
        ),
    ]
