# Generated by Django 5.0.14 on 2026-06-11 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_add_post_number"),
        ("practice", "0010_update_account_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="slug")),
                (
                    "youtube_url",
                    models.URLField(
                        help_text="Full YouTube video URL (e.g. https://www.youtube.com/watch?v=XXXXX)",
                        verbose_name="YouTube URL",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("URGENCIAS", "Urgencias"),
                            ("LACTANCIA", "Lactancia"),
                            ("ALIMENTACION", "Alimentación"),
                            ("SUENO", "Sueño"),
                            ("PRIMEROS_AUXILIOS", "Primeros auxilios"),
                            ("DESARROLLO", "Desarrollo"),
                            ("CONSEJOS", "Consejos"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Video duration in seconds", verbose_name="duration (seconds)"
                    ),
                ),
                (
                    "chapters",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {time_seconds, label} objects",
                        verbose_name="chapters",
                    ),
                ),
                ("thumbnail", models.ImageField(blank=True, upload_to="videos/thumbnails/", verbose_name="thumbnail")),
                (
                    "video_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Auto-assigned on first publish.",
                        null=True,
                        unique=True,
                        verbose_name="video number",
                    ),
                ),
                ("is_published", models.BooleanField(default=False, verbose_name="published")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="published at")),
                ("view_count", models.PositiveIntegerField(default=0, verbose_name="view count")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="videos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "video resource",
                "verbose_name_plural": "video resources",
                "db_table": "video_resources",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
