# Generated by Django 5.0.14 on 2026-06-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_reseed_videos_real_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoresource",
            name="thumbnail",
            field=models.URLField(blank=True, default="", verbose_name="thumbnail"),
        ),
    ]
