# Generated by Django 5.2 on 2026-05-26 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("practice", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="amount")),
                ("currency", models.CharField(default="CLP", max_length=3, verbose_name="currency")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("MERCADOPAGO", "MercadoPago"),
                            ("CASH", "Cash"),
                            ("TRANSFER", "Transfer"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="MercadoPago payment ID or other provider reference",
                        max_length=255,
                        verbose_name="external ID",
                    ),
                ),
                (
                    "external_status",
                    models.CharField(
                        blank=True,
                        help_text="Raw status string from the payment provider",
                        max_length=50,
                        verbose_name="external status",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw provider response payload", verbose_name="metadata"
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="paid at")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment",
                        to="scheduling.appointment",
                        verbose_name="appointment",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="paid by",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Auto-generated. Format: PEDIA-YYYY-NNNNNN",
                        max_length=50,
                        unique=True,
                        verbose_name="invoice number",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(
                        help_text="Denormalized for PDF consistency", max_length=255, verbose_name="patient name"
                    ),
                ),
                ("patient_rut", models.CharField(blank=True, max_length=12, verbose_name="patient RUT")),
                ("service_description", models.CharField(max_length=500, verbose_name="service description")),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="subtotal")),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="tax amount"),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="total")),
                ("issued_at", models.DateTimeField(auto_now_add=True, verbose_name="issued at")),
                ("pdf_file", models.FileField(blank=True, upload_to="invoices/", verbose_name="PDF file")),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="billing.payment",
                        verbose_name="payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
                "db_table": "invoices",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("MERCADOPAGO", "MercadoPago"), ("STRIPE", "Stripe")],
                        max_length=20,
                        verbose_name="provider type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific configuration (access tokens, credentials, etc.)",
                        verbose_name="config",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_providers",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment provider",
                "verbose_name_plural": "payment providers",
                "db_table": "payment_providers",
                "ordering": ["-created_at"],
                "unique_together": {("practice", "provider_type")},
            },
        ),
    ]
