# Generated by Django 5.0.14 on 2026-06-09 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_register_q2_schedules"),
        ("practice", "0010_update_account_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyExpense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RENT", "Arriendo"),
                            ("SUPPLIES", "Insumos médicos"),
                            ("SALARY", "Sueldos/Honorarios"),
                            ("PLATFORM", "Plataformas digitales"),
                            ("INSURANCE", "Seguros"),
                            ("UTILITIES", "Servicios básicos"),
                            ("TAXES", "Impuestos/Patentes"),
                            ("OTHER", "Otros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField(help_text="Monthly amount in CLP")),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_expenses",
                        to="practice.practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly expense",
                "verbose_name_plural": "Monthly expenses",
                "ordering": ["-amount"],
            },
        ),
    ]
