# Generated by Django 5.2 on 2026-05-26 01:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("practice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(max_length=150, verbose_name="last name")),
                ("date_of_birth", models.DateField(verbose_name="date of birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                        max_length=10,
                        verbose_name="gender",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        blank=True,
                        help_text="Chilean national ID (optional). Format: 12345678-9",
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="RUT",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                        verbose_name="blood type",
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, help_text="Known allergies — free text.", verbose_name="allergies"),
                ),
                (
                    "chronic_conditions",
                    models.TextField(
                        blank=True, help_text="Chronic conditions — free text.", verbose_name="chronic conditions"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="General notes from the doctor.", verbose_name="notes"),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="patients/photos/", verbose_name="photo")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "patient",
                "verbose_name_plural": "patients",
                "db_table": "patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("file", models.FileField(upload_to="patients/files/%Y/%m/", verbose_name="file")),
                ("original_filename", models.CharField(max_length=255, verbose_name="original filename")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("LAB_RESULT", "Lab result"),
                            ("IMAGE", "Image"),
                            ("PRESCRIPTION", "Prescription"),
                            ("CERTIFICATE", "Certificate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="file type",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500, verbose_name="description")),
                ("file_size", models.PositiveIntegerField(verbose_name="file size (bytes)")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_files",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "patient file",
                "verbose_name_plural": "patient files",
                "db_table": "patient_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TutorPatient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("MOTHER", "Mother"),
                            ("FATHER", "Father"),
                            ("GUARDIAN", "Guardian"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="relationship",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Marks this tutor as the main point of contact for the patient.",
                        verbose_name="primary contact",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_patients",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_patients",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_patients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="tutor",
                    ),
                ),
            ],
            options={
                "verbose_name": "tutor-patient link",
                "verbose_name_plural": "tutor-patient links",
                "db_table": "tutor_patients",
                "ordering": ["-created_at"],
                "unique_together": {("tutor", "patient")},
            },
        ),
    ]
