# Generated by Django 5.2 on 2026-05-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_sex_at_birth_and_new_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(blank=True, help_text="Street address.", verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="comuna",
            field=models.CharField(blank=True, help_text="e.g. Pucón", max_length=100, verbose_name="comuna"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PARTICULAR", "Particular (self-pay)"),
                    ("FONASA_A", "Fonasa A"),
                    ("FONASA_B", "Fonasa B"),
                    ("FONASA_C", "Fonasa C"),
                    ("FONASA_D", "Fonasa D"),
                    ("ISAPRE_BANMEDICA", "Isapre Banmédica"),
                    ("ISAPRE_COLMENA", "Isapre Colmena Golden Cross"),
                    ("ISAPRE_CONSALUD", "Isapre Consalud"),
                    ("ISAPRE_CRUZ_BLANCA", "Isapre Cruz Blanca"),
                    ("ISAPRE_MASVIDA", "Isapre MásVida"),
                    ("ISAPRE_NUEVA_MASVIDA", "Isapre Nueva MásVida"),
                    ("ISAPRE_ESENCIAL", "Isapre Esencial"),
                    ("ISAPRE_VIDATRES", "Isapre Vida Tres"),
                    ("ISAPRE_BUPA", "Isapre Bupa"),
                    ("ISAPRE_LIFESECURITY", "Isapre Lifesecurity"),
                    ("ISAPRE_ALEMANA_SALUD", "Isapre Alemana Salud"),
                    ("FFAA_CAPREDENA", "FFAA Capredena"),
                    ("FFAA_DIPRECA", "FFAA Dipreca"),
                    ("SIN_PREVISION", "Sin previsión"),
                    ("OTRO", "Otro"),
                ],
                max_length=50,
                verbose_name="insurance",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Patient/tutor contact phone (separate from User.phone).",
                max_length=30,
                verbose_name="phone",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="region",
            field=models.CharField(blank=True, help_text="e.g. La Araucanía", max_length=100, verbose_name="region"),
        ),
    ]
