# Generated by Django 5.0.14 on 2026-06-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_patient_address_alter_patient_comuna_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="phone_prefix",
            field=models.CharField(blank=True, default="+56", max_length=10, verbose_name="phone prefix"),
        ),
    ]
