# Generated by Django 5.0.14 on 2026-06-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_phone_alt_and_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="rut",
            field=models.CharField(
                help_text="Chilean national ID. Format: 12345678-9",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="RUT / document number",
            ),
        ),
    ]
