# Generated by Django 5.0.14 on 2026-06-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_require_patient_rut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("RUT", "RUT (Chilean national ID)"),
                    ("DNI", "Foreign national ID (DNI)"),
                    ("PASAPORTE", "Passport"),
                    ("OTRO", "Other"),
                ],
                default="RUT",
                max_length=15,
                verbose_name="document type",
            ),
        ),
    ]
