# Generated by Django 5.0.14 on 2026-06-08 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_update_document_type_choices"),
        ("practice", "0010_update_account_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoResponsible",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nombre completo")),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("FATHER", "Padre"),
                            ("MOTHER", "Madre"),
                            ("GRANDMOTHER", "Abuela"),
                            ("GRANDFATHER", "Abuelo"),
                            ("UNCLE", "Tío/a"),
                            ("SIBLING", "Hermano/a"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Relación",
                    ),
                ),
                ("rut", models.CharField(blank=True, max_length=20, verbose_name="RUT")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Teléfono")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("can_book", models.BooleanField(default=True, verbose_name="Puede agendar")),
                ("can_pickup", models.BooleanField(default=True, verbose_name="Puede retirar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_responsibles",
                        to="practice.practice",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_responsibles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Co-responsable",
                "verbose_name_plural": "Co-responsables",
                "ordering": ["name"],
            },
        ),
    ]
