# Generated by Django 5.0.14 on 2026-06-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_add_coresponsible_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="apgar_1min",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Apgar score at 1 minute (0–10).", null=True, verbose_name="Apgar 1 min"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="apgar_5min",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Apgar score at 5 minutes (0–10).", null=True, verbose_name="Apgar 5 min"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="birth_length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Length at birth in centimeters.",
                max_digits=4,
                null=True,
                verbose_name="birth length (cm)",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="birth_type",
            field=models.CharField(
                blank=True,
                choices=[("VAGINAL", "Vaginal"), ("CESAREAN", "Cesárea"), ("FORCEPS", "Fórceps"), ("VACUUM", "Vacuum")],
                max_length=20,
                null=True,
                verbose_name="birth type",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="birth_weight_grams",
            field=models.PositiveIntegerField(
                blank=True, help_text="Weight at birth in grams.", null=True, verbose_name="birth weight (grams)"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="feeding_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXCLUSIVE_BREASTFEEDING", "Lactancia materna exclusiva"),
                    ("MIXED", "Mixta"),
                    ("FORMULA", "Fórmula"),
                    ("COMPLEMENTARY", "Alimentación complementaria"),
                    ("SOLID", "Sólidos"),
                ],
                max_length=30,
                null=True,
                verbose_name="feeding type",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="gestational_weeks",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Gestational age at birth in weeks.", null=True, verbose_name="gestational weeks"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="grade",
            field=models.CharField(
                blank=True, default="", help_text="Current school grade or level.", max_length=50, verbose_name="grade"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="school_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of the school the patient attends.",
                max_length=200,
                verbose_name="school name",
            ),
        ),
    ]
