# Generated by Django 5.0.14 on 2026-06-21 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_patient_apgar_1min_patient_apgar_5min_and_more"),
        ("practice", "0010_update_account_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="preferred_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Sede habitual del paciente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_patients",
                to="practice.location",
            ),
        ),
    ]
