# Generated by Django 5.2 on 2026-05-26 01:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Practice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="practices/logos/", verbose_name="logo")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("phone", models.CharField(max_length=30, verbose_name="phone")),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_practices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "practice",
                "verbose_name_plural": "practices",
                "db_table": "practices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("slug", models.SlugField(verbose_name="slug")),
                ("address", models.TextField(verbose_name="address")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                ("region", models.CharField(default="Araucanía", max_length=100, verbose_name="region")),
                ("phone", models.CharField(blank=True, max_length=30, verbose_name="phone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="longitude"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
                "db_table": "locations",
                "ordering": ["name"],
                "unique_together": {("practice", "slug")},
            },
        ),
        migrations.CreateModel(
            name="BlockedSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_datetime", models.DateTimeField(verbose_name="start datetime")),
                ("end_datetime", models.DateTimeField(verbose_name="end datetime")),
                ("reason", models.CharField(blank=True, max_length=200, verbose_name="reason")),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to block all locations.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_slots",
                        to="practice.location",
                        verbose_name="location",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_slots",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "blocked slot",
                "verbose_name_plural": "blocked slots",
                "db_table": "blocked_slots",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("slug", models.SlugField(verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("duration_minutes", models.PositiveIntegerField(default=30, verbose_name="duration (minutes)")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="price")),
                ("is_online_available", models.BooleanField(default=False, verbose_name="available online")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True, related_name="services", to="practice.location", verbose_name="locations"
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "db_table": "services",
                "ordering": ["name"],
                "unique_together": {("practice", "slug")},
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="day of week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="practice.location",
                        verbose_name="location",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "working hours",
                "verbose_name_plural": "working hours",
                "db_table": "working_hours",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("location", "day_of_week")},
            },
        ),
    ]
