# Generated by Django 5.2 on 2026-05-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="display_hours",
            field=models.CharField(
                blank=True,
                help_text="Human-readable hours shown on landing page, e.g. 'Lun – Vie · 09:00 – 19:00'",
                max_length=200,
                verbose_name="display hours",
            ),
        ),
    ]
