# Generated by Django 5.2 on 2026-05-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_location_display_hours"),
    ]

    operations = []
