# Generated by Django 5.0.14 on 2026-05-30 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_service_modality_price_clp"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workinghours",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="workinghours",
            name="break_end",
            field=models.TimeField(
                blank=True,
                help_text="Optional lunch/break window end. Must be within start–end range.",
                null=True,
                verbose_name="break end",
            ),
        ),
        migrations.AddField(
            model_name="workinghours",
            name="break_start",
            field=models.TimeField(
                blank=True,
                help_text="Optional lunch/break window start. Must be within start–end range.",
                null=True,
                verbose_name="break start",
            ),
        ),
        migrations.AddField(
            model_name="workinghours",
            name="is_online",
            field=models.BooleanField(
                default=False,
                help_text="If True, this block is for online consultations (location should be left blank).",
                verbose_name="online block",
            ),
        ),
        migrations.AddField(
            model_name="workinghours",
            name="max_appointments",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Maximum number of bookings allowed within this block.",
                verbose_name="max appointments",
            ),
        ),
        migrations.AddField(
            model_name="workinghours",
            name="slot_duration_minutes",
            field=models.PositiveIntegerField(
                default=45, help_text="Duration of each time slot in minutes.", verbose_name="slot duration (minutes)"
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for online working hours blocks.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_hours",
                to="practice.location",
                verbose_name="location",
            ),
        ),
    ]
