# Generated by Django 5.0.14 on 2026-05-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0005_workinghours_multi_block_breaks_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="modality",
            field=models.CharField(
                choices=[
                    ("PRESENCIAL", "Solo presencial"),
                    ("ONLINE", "Solo online"),
                    ("PRESENCIAL_Y_ONLINE", "Presencial y online"),
                ],
                default="PRESENCIAL",
                max_length=20,
                verbose_name="modality",
            ),
        ),
    ]
