# Generated by Django 5.0.14 on 2026-06-01 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0006_modality_choices_spanish"),
    ]

    operations = [
        migrations.AddField(
            model_name="workinghours",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this block only applies to this specific service. Leave blank for general blocks that apply to all services.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dedicated_working_hours",
                to="practice.service",
                verbose_name="service",
            ),
        ),
    ]
