# Generated by Django 5.0.14 on 2026-06-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0010_update_account_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="is_online_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether online video consultations are available for booking.",
                verbose_name="online consultations enabled",
            ),
        ),
    ]
