# Generated by Django 5.2 on 2026-05-26 14:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("practice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_date", models.DateField(verbose_name="scheduled date")),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("is_online", models.BooleanField(default=False, verbose_name="online appointment")),
                ("cancellation_reason", models.TextField(blank=True, verbose_name="cancellation reason")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="cancelled at")),
                ("confirmed_at", models.DateTimeField(blank=True, null=True, verbose_name="confirmed at")),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True, verbose_name="reminder sent at")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booked_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="booked by",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="doctor",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="practice.location",
                        verbose_name="location",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="practice.service",
                        verbose_name="service",
                    ),
                ),
            ],
            options={
                "verbose_name": "appointment",
                "verbose_name_plural": "appointments",
                "db_table": "appointments",
                "ordering": ["scheduled_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="AutoResponderConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False, verbose_name="active")),
                (
                    "outside_hours_message",
                    models.TextField(
                        blank=True,
                        help_text="Message sent when booking outside working hours",
                        verbose_name="outside hours message",
                    ),
                ),
                (
                    "holiday_message",
                    models.TextField(
                        blank=True,
                        help_text="Message sent during holidays/blocked days",
                        verbose_name="holiday message",
                    ),
                ),
                (
                    "practice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_responder",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "auto responder config",
                "verbose_name_plural": "auto responder configs",
                "db_table": "auto_responder_configs",
            },
        ),
        migrations.CreateModel(
            name="CancellationPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "practice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_policy",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "cancellation policy",
                "verbose_name_plural": "cancellation policies",
                "db_table": "cancellation_policies",
            },
        ),
        migrations.CreateModel(
            name="CancellationTier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "min_hours_before",
                    models.PositiveIntegerField(
                        help_text="Minimum hours before appointment for this tier to apply.",
                        verbose_name="minimum hours before",
                    ),
                ),
                (
                    "penalty_percentage",
                    models.DecimalField(
                        decimal_places=2, help_text="0.00 to 100.00", max_digits=5, verbose_name="penalty percentage"
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="description")),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="scheduling.cancellationpolicy",
                        verbose_name="policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "cancellation tier",
                "verbose_name_plural": "cancellation tiers",
                "db_table": "cancellation_tiers",
                "ordering": ["-min_hours_before"],
            },
        ),
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("preferred_date_start", models.DateField(verbose_name="preferred date start")),
                ("preferred_date_end", models.DateField(blank=True, null=True, verbose_name="preferred date end")),
                ("preferred_time_start", models.TimeField(blank=True, null=True, verbose_name="preferred time start")),
                ("preferred_time_end", models.TimeField(blank=True, null=True, verbose_name="preferred time end")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("NOTIFIED", "Notified"),
                            ("BOOKED", "Booked"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="WAITING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True, verbose_name="notified at")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for any location.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="practice.location",
                        verbose_name="location",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="patients.patient",
                        verbose_name="patient",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="practice.service",
                        verbose_name="service",
                    ),
                ),
            ],
            options={
                "verbose_name": "waitlist entry",
                "verbose_name_plural": "waitlist entries",
                "db_table": "waitlist_entries",
                "ordering": ["created_at"],
            },
        ),
    ]
