# Generated by Django 5.0.14 on 2026-05-29 20:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_service_modality_price_clp"),
        ("scheduling", "0003_appointment_hold_expired_and_new_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True, verbose_name="token")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CONFIRM", "Confirm attendance"),
                            ("CANCEL", "Cancel appointment"),
                            ("RESCHEDULE", "Reschedule appointment"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="used at")),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="scheduling.appointment",
                        verbose_name="appointment",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_tokens",
                        to="practice.practice",
                        verbose_name="practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "appointment token",
                "verbose_name_plural": "appointment tokens",
                "db_table": "appointment_tokens",
            },
        ),
    ]
