# Generated by Django 5.0.14 on 2026-06-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_add_appointment_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="call_platform",
            field=models.CharField(
                blank=True,
                choices=[("WHATSAPP", "WhatsApp"), ("ZOOM", "Zoom")],
                help_text="Platform for online consultations (WhatsApp or Zoom).",
                max_length=20,
                verbose_name="call platform",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                help_text="Video call link for online appointments (auto-generated for Zoom).",
                verbose_name="meeting link",
            ),
        ),
    ]
