# Generated by Django 5.0.14 on 2026-06-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0006_register_q2_schedules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("HOLD", "Hold (pending payment)"),
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CHECKED_IN", "Checked in"),
                    ("IN_PROGRESS", "In progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                    ("NO_SHOW", "No Show"),
                    ("RESCHEDULED", "Rescheduled"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
