# Generated by Django 5.0.14 on 2026-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0007_add_checked_in_and_in_progress_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="priority",
            field=models.CharField(
                choices=[("HIGH", "High"), ("NORMAL", "Normal"), ("LOW", "Low")],
                default="NORMAL",
                max_length=10,
                verbose_name="priority",
            ),
        ),
    ]
