# Generated by Django 5.0.14 on 2026-06-23 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0008_add_priority_to_waitlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="offer_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="offer expires at"),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="offered_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waitlist_offer",
                to="scheduling.appointment",
                verbose_name="offered appointment",
            ),
        ),
        migrations.AlterField(
            model_name="waitlistentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting"),
                    ("NOTIFIED", "Notified"),
                    ("OFFERED", "Offered — pending confirmation"),
                    ("BOOKED", "Booked"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="WAITING",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
